import type { Comment, Episode, RecentEpisode } from './types';

export const mockEpisodes: Episode[] = [
  {
    id: 'ep-1',
    title: 'Начало приключений',
    episodeNumber: 1,
    animeId: 'anime-1',
    animeTitle: 'Attack on Titan',
    duration: 1440, // 24 минуты
    thumbnail: '/images/episodes/attack-on-titan-ep1.jpg',
    videoUrl: '/videos/attack-on-titan-ep1.mp4',
    watchedAt: new Date('2024-01-15T20:30:00'),
    isWatched: true
  },
  {
    id: 'ep-2',
    title: 'Тот день',
    episodeNumber: 2,
    animeId: 'anime-1',
    animeTitle: 'Attack on Titan',
    duration: 1440,
    thumbnail: '/images/episodes/attack-on-titan-ep2.jpg',
    videoUrl: '/videos/attack-on-titan-ep2.mp4',
    watchedAt: new Date('2024-01-16T21:00:00'),
    isWatched: true
  },
  {
    id: 'ep-3',
    title: 'Стена',
    episodeNumber: 3,
    animeId: 'anime-1',
    animeTitle: 'Attack on Titan',
    duration: 1440,
    thumbnail: '/images/episodes/attack-on-titan-ep3.jpg',
    videoUrl: '/videos/attack-on-titan-ep3.mp4',
    watchedAt: new Date('2024-01-17T19:45:00'),
    isWatched: true
  }
];

export const mockRecentEpisodes: RecentEpisode[] = [
  {
    id: 'ep-1',
    title: 'Начало приключений',
    episodeNumber: 1,
    animeId: 'anime-1',
    animeTitle: 'Attack on Titan',
    duration: 1440,
    thumbnail: '/images/episodes/attack-on-titan-ep1.jpg',
    videoUrl: '/videos/attack-on-titan-ep1.mp4',
    watchedAt: new Date('2024-01-15T20:30:00'),
    isWatched: true,
    progress: 100,
    lastWatchedAt: new Date('2024-01-15T20:30:00')
  },
  {
    id: 'ep-2',
    title: 'Тот день',
    episodeNumber: 2,
    animeId: 'anime-1',
    animeTitle: 'Attack on Titan',
    duration: 1440,
    thumbnail: '/images/episodes/attack-on-titan-ep2.jpg',
    videoUrl: '/videos/attack-on-titan-ep2.mp4',
    watchedAt: new Date('2024-01-16T21:00:00'),
    isWatched: true,
    progress: 100,
    lastWatchedAt: new Date('2024-01-16T21:00:00')
  },
  {
    id: 'ep-3',
    title: 'Стена',
    episodeNumber: 3,
    animeId: 'anime-1',
    animeTitle: 'Attack on Titan',
    duration: 1440,
    thumbnail: '/images/episodes/attack-on-titan-ep3.jpg',
    videoUrl: '/videos/attack-on-titan-ep3.mp4',
    watchedAt: new Date('2024-01-17T19:45:00'),
    isWatched: true,
    progress: 85,
    lastWatchedAt: new Date('2024-01-17T19:45:00')
  },
  {
    id: 'ep-4',
    title: 'Первый бой',
    episodeNumber: 4,
    animeId: 'anime-1',
    animeTitle: 'Attack on Titan',
    duration: 1440,
    thumbnail: '/images/episodes/attack-on-titan-ep4.jpg',
    videoUrl: '/videos/attack-on-titan-ep4.mp4',
    watchedAt: new Date('2024-01-18T18:20:00'),
    isWatched: false,
    progress: 45,
    lastWatchedAt: new Date('2024-01-18T18:20:00')
  },
  {
    id: 'ep-5',
    title: 'Выживание',
    episodeNumber: 5,
    animeId: 'anime-1',
    animeTitle: 'Attack on Titan',
    duration: 1440,
    thumbnail: '/images/episodes/attack-on-titan-ep5.jpg',
    videoUrl: '/videos/attack-on-titan-ep5.mp4',
    watchedAt: new Date('2024-01-19T20:15:00'),
    isWatched: true,
    progress: 100,
    lastWatchedAt: new Date('2024-01-19T20:15:00')
  },
  {
    id: 'ep-6',
    title: 'Тренировка',
    episodeNumber: 6,
    animeId: 'anime-1',
    animeTitle: 'Attack on Titan',
    duration: 1440,
    thumbnail: '/images/episodes/attack-on-titan-ep6.jpg',
    videoUrl: '/videos/attack-on-titan-ep6.mp4',
    watchedAt: new Date('2024-01-20T19:30:00'),
    isWatched: false,
    progress: 20,
    lastWatchedAt: new Date('2024-01-20T19:30:00')
  },
  {
    id: 'ep-7',
    title: 'Новые друзья',
    episodeNumber: 1,
    animeId: 'anime-2',
    animeTitle: 'Demon Slayer',
    duration: 1440,
    thumbnail: '/images/episodes/demon-slayer-ep1.jpg',
    videoUrl: '/videos/demon-slayer-ep1.mp4',
    watchedAt: new Date('2024-01-21T21:00:00'),
    isWatched: true,
    progress: 100,
    lastWatchedAt: new Date('2024-01-21T21:00:00')
  },
  {
    id: 'ep-8',
    title: 'Семейные узы',
    episodeNumber: 2,
    animeId: 'anime-2',
    animeTitle: 'Demon Slayer',
    duration: 1440,
    thumbnail: '/images/episodes/demon-slayer-ep2.jpg',
    videoUrl: '/videos/demon-slayer-ep2.mp4',
    watchedAt: new Date('2024-01-22T20:45:00'),
    isWatched: true,
    progress: 100,
    lastWatchedAt: new Date('2024-01-22T20:45:00')
  },
  {
    id: 'ep-9',
    title: 'Путь воина',
    episodeNumber: 3,
    animeId: 'anime-2',
    animeTitle: 'Demon Slayer',
    duration: 1440,
    thumbnail: '/images/episodes/demon-slayer-ep3.jpg',
    videoUrl: '/videos/demon-slayer-ep3.mp4',
    watchedAt: new Date('2024-01-23T19:15:00'),
    isWatched: false,
    progress: 60,
    lastWatchedAt: new Date('2024-01-23T19:15:00')
  },
  {
    id: 'ep-10',
    title: 'Первая миссия',
    episodeNumber: 4,
    animeId: 'anime-2',
    animeTitle: 'Demon Slayer',
    duration: 1440,
    thumbnail: '/images/episodes/demon-slayer-ep4.jpg',
    videoUrl: '/videos/demon-slayer-ep4.mp4',
    watchedAt: new Date('2024-01-24T20:30:00'),
    isWatched: true,
    progress: 100,
    lastWatchedAt: new Date('2024-01-24T20:30:00')
  },
  {
    id: 'ep-11',
    title: 'Встреча с мастерами',
    episodeNumber: 5,
    animeId: 'anime-2',
    animeTitle: 'Demon Slayer',
    duration: 1440,
    thumbnail: '/images/episodes/demon-slayer-ep5.jpg',
    videoUrl: '/videos/demon-slayer-ep5.mp4',
    watchedAt: new Date('2024-01-25T18:50:00'),
    isWatched: true,
    progress: 100,
    lastWatchedAt: new Date('2024-01-25T18:50:00')
  },
  {
    id: 'ep-12',
    title: 'Тренировка с мастерами',
    episodeNumber: 6,
    animeId: 'anime-2',
    animeTitle: 'Demon Slayer',
    duration: 1440,
    thumbnail: '/images/episodes/demon-slayer-ep6.jpg',
    videoUrl: '/videos/demon-slayer-ep6.mp4',
    watchedAt: new Date('2024-01-26T21:20:00'),
    isWatched: false,
    progress: 30,
    lastWatchedAt: new Date('2024-01-26T21:20:00')
  },
  {
    id: 'ep-13',
    title: 'Пробуждение силы',
    episodeNumber: 7,
    animeId: 'anime-2',
    animeTitle: 'Demon Slayer',
    duration: 1440,
    thumbnail: '/images/episodes/demon-slayer-ep7.jpg',
    videoUrl: '/videos/demon-slayer-ep7.mp4',
    watchedAt: new Date('2024-01-27T19:40:00'),
    isWatched: true,
    progress: 100,
    lastWatchedAt: new Date('2024-01-27T19:40:00')
  },
  {
    id: 'ep-14',
    title: 'Новые вызовы',
    episodeNumber: 8,
    animeId: 'anime-2',
    animeTitle: 'Demon Slayer',
    duration: 1440,
    thumbnail: '/images/episodes/demon-slayer-ep8.jpg',
    videoUrl: '/videos/demon-slayer-ep8.mp4',
    watchedAt: new Date('2024-01-28T20:10:00'),
    isWatched: true,
    progress: 100,
    lastWatchedAt: new Date('2024-01-28T20:10:00')
  },
  {
    id: 'ep-15',
    title: 'Битва с демонами',
    episodeNumber: 9,
    animeId: 'anime-2',
    animeTitle: 'Demon Slayer',
    duration: 1440,
    thumbnail: '/images/episodes/demon-slayer-ep9.jpg',
    videoUrl: '/videos/demon-slayer-ep9.mp4',
    watchedAt: new Date('2024-01-29T18:30:00'),
    isWatched: false,
    progress: 75,
    lastWatchedAt: new Date('2024-01-29T18:30:00')
  }
];

export const mockComments: Comment[] = [
  {
    id: 'comment-1',
    userId: 'user-1',
    userName: 'AnimeFan2024',
    userAvatar: '/images/avatars/user1.jpg',
    animeId: 'anime-1',
    episodeNumber: 1,
    content:
      'Отличная первая серия! Очень понравилась анимация и сюжет. Жду продолжения!',
    createdAt: new Date('2024-01-15T22:30:00'),
    updatedAt: new Date('2024-01-15T22:30:00'),
    likes: 15,
    dislikes: 2,
    isLiked: false,
    isDisliked: false
  },
  {
    id: 'comment-2',
    userId: 'user-2',
    userName: 'OtakuMaster',
    userAvatar: '/images/avatars/user2.jpg',
    animeId: 'anime-1',
    episodeNumber: 1,
    content:
      'Согласен! Особенно понравился момент с титанами. Очень атмосферно получилось.',
    createdAt: new Date('2024-01-15T23:15:00'),
    updatedAt: new Date('2024-01-15T23:15:00'),
    likes: 8,
    dislikes: 0,
    isLiked: true,
    isDisliked: false,
    parentId: 'comment-1'
  },
  {
    id: 'comment-3',
    userId: 'user-3',
    userName: 'WeebLife',
    userAvatar: '/images/avatars/user3.jpg',
    animeId: 'anime-1',
    content:
      'В целом аниме хорошее, но есть моменты где можно было бы лучше проработать персонажей. Впрочем, для первого сезона неплохо.',
    createdAt: new Date('2024-01-16T10:20:00'),
    updatedAt: new Date('2024-01-16T10:20:00'),
    likes: 5,
    dislikes: 3,
    isLiked: false,
    isDisliked: false
  },
  {
    id: 'comment-4',
    userId: 'user-4',
    userName: 'MangaReader',
    userAvatar: '/images/avatars/user4.jpg',
    animeId: 'anime-1',
    episodeNumber: 2,
    content:
      'Вторая серия еще лучше! Действие нарастает, персонажи раскрываются. Рекомендую всем!',
    createdAt: new Date('2024-01-16T20:45:00'),
    updatedAt: new Date('2024-01-16T20:45:00'),
    likes: 12,
    dislikes: 1,
    isLiked: false,
    isDisliked: false
  },
  {
    id: 'comment-5',
    userId: 'user-5',
    userName: 'AnimeCritic',
    userAvatar: '/images/avatars/user5.jpg',
    animeId: 'anime-1',
    content:
      'Анимация на высоте, но сюжет местами предсказуем. Все же стоит посмотреть, если любите жанр.',
    createdAt: new Date('2024-01-17T14:30:00'),
    updatedAt: new Date('2024-01-17T14:30:00'),
    likes: 7,
    dislikes: 4,
    isLiked: false,
    isDisliked: false
  },
  {
    id: 'comment-6',
    userId: 'user-6',
    userName: 'NewbieOtaku',
    userAvatar: '/images/avatars/user6.jpg',
    animeId: 'anime-1',
    episodeNumber: 3,
    content:
      'Мой первый опыт с этим жанром. Пока что очень нравится! Подскажите, что еще посмотреть в похожем стиле?',
    createdAt: new Date('2024-01-18T16:20:00'),
    updatedAt: new Date('2024-01-18T16:20:00'),
    likes: 20,
    dislikes: 0,
    isLiked: true,
    isDisliked: false
  }
];
